activies/urls.py
from django.urls import path
from . import views
urlpatterns = [
    # la partie initiale 
    path('', views.index, name = 'index' ),
    path('login/', views.loginpage, name = 'login'),
    path('logout/', views.logoutpage, name = 'logout'),
    path('createUser/', views.createUser, name = 'createUser'),
    path('user_profil/', views.user_profil, name = 'user_profil'),

    path('achat/', views.Achat, name = 'achat'),
    path('add_Achat/', views.add_Achat, name = 'add_Achat'),
    path('update_achat/<int:id>', views.update_achat, name = 'update_achat'),
    path('facture/<int:id>', views.facture, name = 'facture'),

    path('vente/', views.vente, name = 'vente'),
    path('add_vente/', views.add_vente, name = 'add_vente'),
    path('update_vente<int:id>', views.update_vente, name = 'update_vente'),
    
    path('vente_etain/', views.vente_etain, name = 'vente_etain'),
    path('add_vente_etain/', views.add_vente_etain, name = 'add_vente_etain'),
    path('update_vente_etain/<int:id>', views.update_vente_etain, name = 'update_vente_etain'),

    path('commandes/', views.commandes, name = 'commandes'),
    path('add_commande/', views.add_commande, name = 'add_commande'),
    path('update_commande/<int:id>', views.update_commande, name = 'update_commande'),

    path('fondrerie/', views.fondrerie, name = 'fondrerie'),
    path('add_fondre/', views.add_fondre, name = 'add_fondre'),
    path('update_fondre/<int:id>', views.update_fondre, name = 'update_fondre'),

    path('rafinage/', views.rafinage, name = 'rafinage'),
    # path('add_rafinage/', views.add_rafinage, name = 'add_rafinage'),
    path('update_rafinage/<int:id>', views.update_rafinage, name = 'update_rafinage'),


  
]

smartamm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('activies.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

activies/models.py
from django.db import models
from django.contrib.auth.models import User
import statistics
import datetime


class commande(models.Model):
    STATUS = (
('livree','livree'),
('non_livree','non_livree')
    )

    produits = models.ForeignKey("produits", on_delete = models.CASCADE)
    clients = models.ForeignKey("clients", on_delete = models.CASCADE, related_name = 'client')
    status = models.CharField(max_length = 20, choices=STATUS)
    prix_vente = models.FloatField( default=0.0)
    quantite = models.FloatField(default=0.0)
    teneur = models.FloatField(default=0.0)
    date_commander = models.DateTimeField(auto_now_add=True)
    date_modifier = models.DateTimeField(auto_now=True)
    prix_total = models.FloatField(default=0.0)
    
    def __str__(self) :
        return self.produits.nomProdui
    

class produits(models.Model):
    nomProdui = models.CharField(max_length = 20)
    date_creation = models.DateTimeField(auto_now = True)
    def __str__(self) :
        return self.nomProdui

class clients(models.Model):

    nom_clients = models.CharField(max_length = 50)
    sexe = models.CharField(max_length = 10, default= 'homme')
    telephone = models.CharField(max_length = 50)
    created_at  =  models.DateTimeField(auto_now = True)
    def __str__(self) :
        return self.nom_clients
    class Meta():
        ordering = ['-created_at']

class fournisseurs(models.Model):
 
    nom_fournisseurs = models.CharField(max_length = 50)
    sexe = models.CharField(max_length = 10, default= 'homme')
    telephone = models.CharField(max_length = 50)
    created_at  =  models.DateTimeField(auto_now = True)

    def __str__(self) :
        return self.nom_fournisseurs

class users(models.Model):
    user = models.OneToOneField(User, null=True, blank=True,on_delete=models.CASCADE)
    name = models.CharField(max_length = 20)
    post_nom =models.CharField(max_length = 20)
    ville =models.CharField(max_length = 20) 
    matricule = models.CharField(max_length = 20)
    telephone = models.CharField(max_length = 20)
    email =models.CharField(max_length = 20)
    image_pic = models.ImageField(null = True, blank=True, default='media/prof.jpeg', upload_to='media') 
    date_created = models.DateTimeField(default= datetime.datetime.today())
    def __str__(self) :
        return self.name

class sorties(models.Model):
    user = models.ForeignKey(users, null=True, blank=True,on_delete=models.SET_NULL)
    clients = models.ForeignKey("clients", on_delete = models.CASCADE, related_name = 'clients')
    produits = models.ForeignKey("produits", on_delete = models.CASCADE, related_name = 'produit')
    quantite_en_kg = models.FloatField(default=0.0, null=False)
    prix_vente_en_dollard = models.FloatField(default=0.0, null=False)
    teneur_en_pourcentage = models.FloatField(default=0.0, null=False)
    # tvaPourcentage = models.FloatField(default=0.0, null=False)
    date_sortie  =  models.DateTimeField(auto_now=True)
    prix_total_en_dollard = models.FloatField(default=0.0)
    class Meta():
        ordering = ['-date_sortie']

class entrees(models.Model):
    user = models.ForeignKey(users, null=True, blank=True, on_delete=models.CASCADE)
    fournisseurs = models.ForeignKey("fournisseurs", on_delete = models.CASCADE)
    numero_tag = models.CharField(max_length = 20)
    source_minier = models.CharField(max_length=200, null=True)
    produits = models.ForeignKey("produits", on_delete = models.CASCADE)
    teneur_en_pourcentage = models.FloatField(default=0.0, null = False)
    quantite_en_kg = models.FloatField( default=0.0, null = False)
    prix_achat_en_dollard = models.FloatField(default=0.0, null = False)
    prix_total_en_dollard = models.FloatField(default=0.0)
    montant_depanses_en_dollard  = models.FloatField(null=True, default = 0.0)
    depanses = models.ManyToManyField("depanses",)
    descriptions = models.TextField(max_length = 200, null=True)
    date_entrer =  models.DateTimeField(auto_now = True)
    # date_entrer  =  models.DateTimeField(auto_now =True, default= datetime.datetime.now())
    class Meta():
        ordering = ['-date_entrer']
class depanses(models.Model):
    name = models.CharField(max_length=222, default='', null=True)
    def __str__(self) :
        return self.name

class stock(models.Model):
    montant = models.FloatField()
    produits =  models.ForeignKey("produits", on_delete = models.CASCADE)


class transformations(models.Model):
    user = models.ForeignKey(users, null=True, blank=True,on_delete=models.SET_NULL)
    produits =  models.ForeignKey("produits", on_delete = models.CASCADE)
    fourcasterie = models.ForeignKey("fourcasterie", on_delete = models.CASCADE)
    fourrafine = models.ForeignKey("fourrafine", on_delete = models.CASCADE, null=True)
    quantite_entrer_casterie_en_kg = models.FloatField( default = 0.0 )
    quantite_sortie_casterie_en_kg = models.FloatField( default = 0.0 )
    quantite_entrer_etain_en_kg = models.FloatField( default = 0.0 )
    quantite_sortie_etain_en_kg = models.FloatField( default = 0.0 )
    entrant_casterie_en_kg = models.FloatField( default = 0.0 )
    entrant_etain_en_kg = models.FloatField( default = 0.0 )
    teneur_casterie_en_pourcentage = models.FloatField( default = 0.0 )
    
    teneur_etain_en_pourcentage = models.FloatField( default = 0.0 ) 
    date_entrer =  models.DateTimeField(auto_now_add = True)
    date_sortie =  models.DateTimeField(auto_now = True)


class fourcasterie(models.Model):
    libelle = models.CharField(max_length = 255,default = 'SF')
    date_create  =  models.DateTimeField(auto_now = True)

    def __str__(self) :
        return self.libelle

class fourrafine(models.Model):
    libelle = models.CharField(max_length = 255, default = 'null')
    date_create = models.DateTimeField(auto_now = True)

    def __str__(self) :
        return self.libelle







    

activies/templates/pages/ajout_commande.html
{% extends 'pages/base.html' %}


{% block index %}
<main id="main" class="main">

    <div class="pagetitle">

        <h1>Enregistrer une commande pour la  casterie </h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index'%} ">Accueil</a></li>
                <li class="breadcrumb-item"><a href="{% url 'add_vente'%} ">vendre la casterie</a></li>
                <li class="breadcrumb-item"><a href="{% url 'index'%} ">transformer la casterie</a></li>
                <li class="breadcrumb-item"><a href="{% url 'achat'%} ">table d'achat</a></li>
                <li class="breadcrumb-item active">commande de la casterie</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <div class="contenair">
        <div class="row">
            <div class="col-md-12">
                <div class="card ">
                  <section class="section">
            <div class="row">
              <div class="col-lg-12">
      
                <div class="card">
                  <div class="card-body">
                  <div class="contenair">
                    <div class="row">
                      <div class="col-md-3">

                      </div>
                      <div class="col-md-6 ">
                      
                        <div class="class">
                          <p class="alert alert-success text-center ">la teneur moyenne de la cesterie est de {{moyenne_teneur}}</p>
                        </div>
                        
                        {% for message in messages %}
                        <div class="class">
                          <p class="alert alert-danger text-center ">{{message}}</p>
                        </div>
                        {% endfor %}
                      <form class="row g-3 align-items-center" method="post" action="">
                     {% csrf_token %}
                     <div class="col-12 form-control">
                        {{form.as_p}}
                        
                        <button class="btn btn-primary" type="submit">Submit form</button>
                      </div>
                    
                    </form>
                      </div>
                      <div class="col-md-3">
                    
                      </div>
                    
                    </div>
                  
                  </div>  
                   
                    
                </div>
            </div>
        </div>
    </div>


</main>
{% load static %}
<script type="text/javascript" src="{% static './assets/js/jquery-3.0.0.min.js' %}"></script>
<script>
  $(document).ready(function () {
  $("#id_quantite_en_kg, #id_prix_vente_en_dollard").keyup(function () {
   
    var total = 0.0;
    var qut = Number($("#id_quantite_en_kg").val());
    var prix = Number($("#id_prix_vente_en_dollard").val());
    total = qut * prix ;
    $("#id_teneur_en_pourcentage").val(parseFloat("{{moyenne_teneur}}"));
    $("#id_prix_total_en_dollard").val(parseFloat(total));
  })
})
</script>



{% endblock %}

activies/templates/pages/ajout_rafinage.html
{% extends 'pages/base.html' %}


{% block index %}
<main id="main" class="main">

    <div class="pagetitle">

        <h1>Achat de la casterie </h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index'%} ">Accueil</a></li>
                <li class="breadcrumb-item"><a href="{% url 'index'%} ">vendre la casterie</a></li>
                <li class="breadcrumb-item"><a href="{% url 'index'%} ">transformer la casterie</a></li>
                <li class="breadcrumb-item"><a href="{% url 'achat'%} ">table d'achat</a></li>
                <li class="breadcrumb-item active">faites l'achat ici</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <div class="contenair">
        <div class="row">
            <div class="col-md-12">
                <div class="card ">
                  <section class="section">
            <div class="row">
              <div class="col-lg-12">
      
                <div class="card">
                  <div class="card-body">
                  <div class="contenair">
                    <div class="row">
                      <div class="col-md-3">

                      </div>
                      <div class="col-md-6 ">
                        <div class="class">
                          <p class="alert alert-success text-center "> de transformations</p>
                        </div>
                        <div class="class">
                      <p class="alert alert-success text-center ">la qquantité sortie au four de rafinage est de {{request.all_fondrerie.id}}</p>
                    </div>
                      <form class="row g-3 align-items-center" method="post" action="">
                     {% csrf_token %}
                     
                     <div class="col-12 form-control">
                        {{form}}
                        
                        <button class="btn btn-primary" type="submit">sumettre</button>
                      </div>
                    
                    </form>
                      </div>
                      <div class="col-md-3">
                    
                      </div>
                    
                    </div>
                  
                  </div>  
                   
                    
                </div>
            </div>
        </div>
    </div>


</main>
{% load static %}
<script type="text/javascript" src="{% static './assets/js/jquery-3.0.0.min.js' %}"></script>
<script>
  $(document).ready(function () {
  $("#id_quantite_entrer_casterie").keyup(function () {
   
    
    var qut = $("#id_quantite_entrer_casterie").val();
   
    $("#id_teneur_casterie").val(parseFloat('{{moyenne_teneur}}'));
  })
})
</script>



{% endblock %}

activies/templates/pages/ajout_vente.html
{% extends 'pages/base.html' %}


{% block index %}
<main id="main" class="main">

    <div class="pagetitle">

        <h1>vente de la casteterie </h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index'%} ">Accueil</a></li>
                <li class="breadcrumb-item"><a href="{% url 'index'%} ">vendre la casterie</a></li>
                <li class="breadcrumb-item"><a href="{% url 'index'%} ">transformer la casterie</a></li>
                <li class="breadcrumb-item"><a href="{% url 'achat'%} ">table d'achat</a></li>
                <li class="breadcrumb-item active">faites l'achat ici</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <div class="contenair">
        <div class="row">
            <div class="col-md-12">
                <div class="card ">
                  <section class="section">
            <div class="row">
              <div class="col-lg-12">
      
                <div class="card">
                  <div class="card-body">
                  <div class="contenair">
                    <div class="row">
                      <div class="col-md-3">

                      </div>
                      <div class="col-md-6 ">
                      
                        <div class="class">
                          <p class="alert alert-success text-center ">la teneur moyenne de la cesterie est de {{moyenne_teneur}}</p>
                        </div>
                        
                        {% for message in messages %}
                        <div class="class">
                          <p class="alert alert-danger text-center ">{{message}}</p>
                        </div>
                        {% endfor %}
                      <form class="row g-3 align-items-center" method="post" action="">
                     {% csrf_token %}
                     <div class="col-12 form-control">
                        {{form.as_p}}
                        
                        <button class="btn btn-primary" type="submit">Submit form</button>
                      </div>
                    
                    </form>
                      </div>
                      <div class="col-md-3">
                    
                      </div>
                    
                    </div>
                  
                  </div>  
                   
                    
                </div>
            </div>
        </div>
    </div>


</main>
{% load static %}
<script type="text/javascript" src="{% static './assets/js/jquery-3.0.0.min.js' %}"></script>
<script>
  $(document).ready(function () {
  $("#id_quantite_en_kg, #id_prix_vente_en_dollard").keyup(function () {
   
    var total = 0.0;
    var qut = Number($("#id_quantite_en_kg").val());
    var prix = Number($("#id_prix_vente_en_dollard").val());
    total = qut * prix ;
    $("#id_teneur_en_pourcentage").val(parseFloat("{{moyenne_teneur}}"));
    $("#id_prix_total_en_dollard").val(parseFloat(total));
  })
})
</script>



{% endblock %}

activies/templates/pages/ajout_vente_etain.html
{% extends 'pages/base.html' %}


{% block index %}
<main id="main" class="main">

    <div class="pagetitle">

        <h1>vente de l'etain </h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index'%} ">Accueil</a></li>
                <li class="breadcrumb-item"><a href="{% url 'index'%} ">vendre la casterie</a></li>
                <li class="breadcrumb-item"><a href="{% url 'index'%} ">transformer la casterie</a></li>
                <li class="breadcrumb-item"><a href="{% url 'achat'%} ">table d'achat</a></li>
                <li class="breadcrumb-item active">faites vente ici</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <div class="contenair">
        <div class="row">
            <div class="col-md-12">
                <div class="card ">
                  <section class="section">
            <div class="row">
              <div class="col-lg-12">
      
                <div class="card">
                  <div class="card-body">
                  <div class="contenair">
                    <div class="row">
                      <div class="col-md-3">

                      </div>
                      <div class="col-md-6 ">
                      
                        <div class="class">
                          <p class="alert alert-success text-center ">la teneur moyenne de la cesterie est de {{moyenne_teneur}}</p>
                        </div>
                        
                        {% for message in messages %}
                        <div class="class">
                          <p class="alert alert-danger text-center ">{{message}}</p>
                        </div>
                        {% endfor %}
                      <form class="row g-3 align-items-center" method="post" action="">
                     {% csrf_token %}
                     <div class="col-12 form-control">
                        {{form.as_p}}
                        
                        <button class="btn btn-primary" type="submit">Submit form</button>
                      </div>
                    
                    </form>
                      </div>
                      <div class="col-md-3">
                    
                      </div>
                    
                    </div>
                  
                  </div>  
                   
                    
                </div>
            </div>
        </div>
    </div>


</main>
{% load static %}
<script type="text/javascript" src="{% static './assets/js/jquery-3.0.0.min.js' %}"></script>
<script>
  $(document).ready(function () {
  $("#id_quantite_en_kg, #id_prix_vente_en_dollard").keyup(function () {
   
    var total = 0.0;
    var qut = Number($("#id_quantite_en_kg").val());
    var prix = Number($("#id_prix_vente_en_dollard").val());
    total = qut * prix ;
    $("#id_teneur_en_pourcentage").val(parseFloat("{{moyenne_teneur}}"));
    $("#id_prix_total_en_dollard").val(parseFloat(total));
  })
})
</script>



{% endblock %}

activies/templates/pages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>AMM</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href=" {% static './assets/img/favicon.png' %} " rel="icon">
  <link href=" {% static './assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">


  <!-- Vendor CSS Files -->
  <link href="{% static './assets/vendor/bootstrap/css/bootstrap.min.css ' %}" rel="stylesheet">
  <link href="{% static './assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static './assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static './assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static './assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static './assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static './assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
 
  <link href="{% static './assets/css/main.css' %}" rel="stylesheet">
 
</head>

<body>


    <header id="header" class="header fixed-top d-flex align-items-center">
    
        <div class="d-flex align-items-center justify-content-between">
          <a href="../ " class="logo d-flex align-items-center">
            <img src="{% static './assets/img/logo.png '%}" alt="">
            <span class="d-none d-lg-block">SMART AMM</span>
          </a>
          <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->
    
        <nav class="header-nav ms-auto">
          <ul class="d-flex align-items-center">
    
            <!-- End Search Icon-->
    
            <li class="nav-item dropdown">
                
              <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                <i class="bi bi-bell"></i>
                
                <span class="badge bg-primary badge-number">0</span>
    
              </a><!-- End Notification Icon -->
    
              <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                <li class="dropdown-header">
                  vous avez une alerte
                 
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
    
                <li class="notification-item">
                  <i class="bi bi-exclamation-circle text-warning"></i>
                  <div>
                    <h4 style="color: red;">alerte</h4>
                    <p>{{sango}}</p>
                    <p>30 min. ago</p>
                  </div>
                 
                </li>
    
                
              </ul><!-- End Notification Dropdown Items -->
    
    
            <li class="nav-item dropdown pe-3">
    
              <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                <img src="{{ request.user.users.image_pic.url }}" alt="Profile" class="rounded-circle">
                <span class="d-none d-md-block dropdown-toggle ps-2">Bienvenu {{request.user }}</span>
              </a><!-- End Profile Iamge Icon -->
    
              <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                <li class="dropdown-header">
                  <h6>{{request.user}}</h6>
                  {% if request.user.is_staff %}
                  <h3>Administarteur</h3>
                  {% else %}
                  <h3>Agent</h3>
                  {% endif %}
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
    
                <li>
                  <a class="dropdown-item d-flex align-items-center" href="{% url 'user_profil'%}">
                    <i class="bi bi-person"></i>
                    <span>Profile</span>
                  </a>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
    
                <li>
                  <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                    <i class="bi bi-gear"></i>
                    <span>paramettre de count</span>
                  </a>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
    
                <li>
                  <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                    <i class="bi bi-question-circle"></i>
                    <span>aide ?</span>
                  </a>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
    
                <li>
                  <a class="dropdown-item d-flex align-items-center" href="{% url 'logout'%}">
                    <i class="bi bi-box-arrow-right"></i>
                    <span>deconnexion </span>
                  </a>
                </li>
    
              </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->
    
          </ul>
        </nav><!-- End Icons Navigation -->
    
      </header><!-- End Header -->

<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="../  ">
          <i class="bi bi-grid"></i>
          <span>tableau de bord</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Menu</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'vente' %}"">
              <i class="bi bi-circle"></i><span>Vente casterie</span>
            </a>
          </li>
          
            <li>
              <a href="">
                <i class="bi bi-circle"></i><span>Vente etain</span>
              </a>
            </li>
            <li>
            <a href="{% url 'achat' %}">
              <i class="bi bi-list"></i><span>Achat casterie</span>
            </a>
          </li>

          <li>
            <a href="">
              <i class="bi bi-circle"></i><span>fondrerie</span>
            </a>
          </li>
          <li>
            <a href="{% url 'rafinage' %}">
              <i class="bi bi-circle"></i><span>rafinage</span>
            </a>
          </li>
      
        </li>
        <li>
          <a href="">
            <i class="bi bi-circle"></i><span>commande</span>
          </a>
        </li>
    
      </li>
        
         <!-- End Blank Page Nav -->

    </ul>
<li class="nav-item">
          <a class="nav-link collapsed" data-bs-target="#components-navd" data-bs-toggle="collapse" href="#">
            <i class="bi bi-menu-button-wide"></i><span>paramettre</span><i class="bi bi-chevron-down ms-auto"></i>
          </a>
          <ul id="components-navd" class="nav-content collapse " data-bs-parent="#sidebar-nav">
            <li>
              <a href="../createUser/">
                {% if request.user.is_staff %}
                <i class="bi bi-circle"></i><span>creer un utilisateur</span>
                {% endif %}
              </a>
            </li>
            <li>
              <a href="{% url 'logout' %}">
                <i class="bi bi-circle"></i><span>deconnexion</span>
              </a>
            </li>
          </ul>
        </li>
  </aside>
  {% block index %}

{% endblock  %}
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>AMM</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://israelmavu.netlify.com/">MAVDEV</a>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static './assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static './assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static './assets/vendor/chart.js/chart.min.js' %}"></script>
  <script src="{% static './assets/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static './assets/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static './assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static './assets/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static './assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static './assets/js/main.js' %}"></script>
  <script src="{% static './assets/js/jquery-3.0.0.min.js' %}"></script>

</body>

</html>